### ISSUE TITLE
`get_timeseries_essentials` method needs to return proxy string rather than ontology URL

### ISSUE THREAD

**Issue by khider** [LinkedEarth/pylipd#58] opened 2024-05-10 17:52 UTC
For instance,

![image](https://github.com/LinkedEarth/pylipd/assets/11758571/709c20ff-ec75-4207-af05-649d28dac992)

**Comment by varunratnakar** [comment] 2024-05-11 09:47
The proxy should be fixed now

<img width="1059" alt="Screenshot 2024-05-11 at 3 16 48 PM" src="https://github.com/LinkedEarth/pylipd/assets/27664194/3ddb9dcb-7965-4d0e-b896-2fa48e285552">

**Comment by varunratnakar** [comment] 2024-05-14 06:32
Maybe duplicate of https://github.com/LinkedEarth/pylipd/issues/57

**Closed** 2024-05-16 00:15 UTC
Labels: enhancement
